# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 77aa676dfa84c7b95da0bb43ff998b6e55ad70f5437cebabbf3a2b284fc4ffc7b223756804103a73e519a3408d35dc3547e9e7fabe82c57d810a88f69e4ba10b

test:
  secret_key_base: 4deb690854998a77fc77c692baf80b2e0e4f4b6d78c71aa3c80cae86c559fb8aae2f9343ec40af02c377d8380b85eaca0889bd20bff8a99cc3db3bc14a18efa2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
